### 지난 1년간 가장 많이 참여한 여가활동 1~5순위 데이터만 추가한경우

1. 데이터 전처리
-> csv or xlsx 파일의 정보들을 테이터화

2.

In [1]:
import pandas as pd

### 데이터 전처리1
코드와 정보값을 구분하여 정리

In [ ]:
# 엑셀 파일을 읽어옵니다
code_df = pd.read_excel("../../data/코드정의서.xlsx")  # 파일 경로를 지정하세요

# 데이터프레임을 리스트로 변환합니다
data_list = code_df.values.tolist()

# code_dict에 키-값 형태로 코드와 정보를 저장
code_dict = {}

for key, value in data_list:
    code_dict[key] = value

code_dict

{'Q1_1': '전시회 관람(미술, 사진, 건축, 디자인 등)',
 'Q1_2': '박물관 관람',
 'Q1_3': '음악연주회 관람(클래식, 오페라 등)',
 'Q1_4': '전통예술공연 관람(국악, 민속놀이 등)',
 'Q1_5': '연극공연 관람(뮤지컬 포함)',
 'Q1_6': '무용공연 관람',
 'Q1_7': '영화관람',
 'Q1_8': '연예공연 관람(쇼, 콘서트, 마술 쇼 등)',
 'Q1_9': '문학행사참여',
 'Q1_10': '글짓기/독서토론',
 'Q1_11': '미술활동(그림, 서예, 조각, 디자인, 도예, 만화 등)',
 'Q1_12': '악기연주/노래교실',
 'Q1_13': '전통예술 배우기(사물놀이, 줄타기 등)',
 'Q1_14': '사진촬영(디지털카메라 포함)',
 'Q1_15': '춤/무용(발레, 한국무용, 현대무용, 방송댄스, 스트릿댄스, 비보잉 등)',
 'Q1_16': '스포츠 경기 직접관람- 경기장방문관람(축구, 야구,농구, 배구 등)',
 'Q1_17': '스포츠 경기 간접관람- TV, DMB를 통한관람(축구, 야구, 농구, 배구 등)',
 'Q1_18': '격투 스포츠 경기관람(태권도, 유도, 합기도, 검도,권투 등)',
 'Q1_19': '온라인게임 경기관람(e-스포츠 경기 포함)',
 'Q1_20': '농구, 배구, 야구, 축구, 족구',
 'Q1_21': '테니스, 스쿼시',
 'Q1_22': '당구/포켓볼',
 'Q1_23': '볼링, 탁구',
 'Q1_24': '골프',
 'Q1_25': '수영',
 'Q1_26': '윈드서핑, 수상스키, 스킨스쿠버다이빙, 래프팅, 요트',
 'Q1_27': '스노보드, 스키 등',
 'Q1_28': '아이스스케이트, 아이스하키 등',
 'Q1_29': '헬스(보디빌딩)/에어로빅',
 'Q1_30': '요가/필라테스/태보',
 'Q1_31': '배드민턴/줄넘기/맨손, 스트레칭 체조/훌라후프',
 'Q1_32': '육상/조깅/속보',
 'Q1_33': '격투 스포츠(태권도, 유도, 합기도, 검도, 권투 등)',
 'Q1_34': '댄스스포츠(탱고, 왈츠, 자이브, 맘보,폴카, 차차차등)',
 'Q1_35': '사이클링/산악자전거',
 'Q1_36': '인라인스케이트',
 'Q1_37': '승마, 암벽등반, 철인삼종경기, 서바이벌',
 'Q1_38': '문화유적방문(고궁, 절, 유적지 등)',
 'Q1_39': '자연명승 및 풍경 관람',
 'Q1_40': '삼림욕',
 'Q1_41': '국내캠핑',
 'Q1_42': '해외여행',
 'Q1_43': '소풍/야유회',
 'Q1_44': '온천/해수욕',
 'Q1_45': '유람선 타기',
 'Q1_46': '테마파크가기/놀이공원/동물원/식물원 가기',
 'Q1_47': '지역축제 참가',
 'Q1_48': '자동차 드라이브',
 'Q1_49': '수집활동(스크랩 포함)',
 'Q1_50': '생활공예(십자수, 비즈공예, D.I.Y, 꽃꽂이 등)',
 'Q1_51': '요리하기/다도',
 'Q1_52': '반려동물 돌보기',
 'Q1_53': '노래방 가기',
 'Q1_54': '인테리어(집, 자동차 등)',
 'Q1_55': '등산',
 'Q1_56': '낚시',
 'Q1_57': '홈페이지/블로그 관리',
 'Q1_58': '인터넷 검색/1인 미디어 제작/SNS/영상편집',
 'Q1_59': '게임(온라인/모바일/콘솔게임 등)',
 'Q1_60': '보드게임/퍼즐/큐브 맞추기',
 'Q1_61': '바둑/장기/체스',
 'Q1_62': '겜블(경마, 경륜, 카지노, 카드놀이, 고스톱, 마작 등)/복권구입',
 'Q1_63': '쇼핑/외식',
 'Q1_64': '음주',
 'Q1_65': '독서(웹소설 포함)',
 'Q1_66': '만화보기(웹툰 포함)',
 'Q1_67': '미용(피부관리, 헤어관리, 네일아트, 마사지, 성형 등)',
 'Q1_68': '어학/기술/자격증 취득 공부/학원 등 이용',
 'Q1_69': '이색/테마카페 체험(방탈출, VR, 낚시카페 등)',
 'Q1_70': '원예(화분, 화단가꾸기 등)',
 'Q1_71': '산책 및 걷기',
 'Q1_72': '목욕/사우나/찜질방',
 'Q1_73': '낮잠',
 'Q1_74': 'TV시청(IPTV 포함)',
 'Q1_75': '모바일 컨텐츠, 동영상, VOD 시청, OTT 시청',
 'Q1_76': '라디오/팟캐스트 청취',
 'Q1_77': '음악 감상',
 'Q1_78': '신문/잡지보기',
 'Q1_79': '아무것도 안 하기',
 'Q1_80': '사회봉사활동',
 'Q1_81': '종교활동',
 'Q1_82': '클럽/나이트/디스코/캬바레 가기',
 'Q1_83': '가족 및 친지방문',
 'Q1_84': '잡담/통화하기/문자보내기(모바일 메신저 메시지 사용 포함)',
 'Q1_85': '계모임/동창회/사교(파티)모임',
 'Q1_86': '친구만남/이성교제/미팅/소개팅',
 'Q1_87': '동호회 모임',
 'Q1_88': '위에서 분류되지 않은 기타 여가활동',
 'Q1_89': '독서/만화책(웹툰)보기(2014,2016,2018)',
 'Q1_90': '이성교제(데이트)/미팅/소개팅(2014,2016,2018)',
 'Q1_91': '친구만남/동호회 모임(2014,2016,2018)',
 'Q2_1_1': '지난 1년간 가장 많이 참여한 여가활동 (1순위)',
 'Q2_1_2': '지난 1년간 가장 많이 참여한 여가활동 (2순위)',
 'Q2_1_3': '지난 1년간 가장 많이 참여한 여가활동 (3순위)',
 'Q2_1_4': '지난 1년간 가장 많이 참여한 여가활동 (4순위)',
 'Q2_1_5': '지난 1년간 가장 많이 참여한 여가활동 (5순위)',
 'Q2_2_1_T': '지난 1년간 가장 많이 참여한 여가활동 동반자 - 기타(1순위)',
 'Q2_2_2_T': '지난 1년간 가장 많이 참여한 여가활동 동반자 - 기타(2순위)',
 'Q2_2_3_T': '지난 1년간 가장 많이 참여한 여가활동 동반자 - 기타(3순위)',
 'Q2_2_4_T': '지난 1년간 가장 많이 참여한 여가활동 동반자 - 기타(4순위)',
 'Q2_2_5_T': '지난 1년간 가장 많이 참여한 여가활동 동반자 - 기타(5순위)',
 'Q2_3_1': '지난 1년간 가장 많이 참여한 여가활동 빈도(1순위)',
 'Q2_3_2': '지난 1년간 가장 많이 참여한 여가활동 빈도(2순위)',
 'Q2_3_3': '지난 1년간 가장 많이 참여한 여가활동 빈도(3순위)',
 'Q2_3_4': '지난 1년간 가장 많이 참여한 여가활동 빈도(4순위)',
 'Q2_3_5': '지난 1년간 가장 많이 참여한 여가활동 빈도(5순위)',
 'Q2_3_1_T': '지난 1년간 가장 많이 참여한 여가활동 빈도 - 기타(1순위)',
 'Q2_3_2_T': '지난 1년간 가장 많이 참여한 여가활동 빈도 - 기타(2순위)',
 'Q2_3_3_T': '지난 1년간 가장 많이 참여한 여가활동 빈도 - 기타(3순위)',
 'Q2_3_4_T': '지난 1년간 가장 많이 참여한 여가활동 빈도 - 기타(4순위)',
 'Q2_3_5_T': '지난 1년간 가장 많이 참여한 여가활동 빈도 - 기타(5순위)',
 'Q2_4_1_1_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 시간(1순위)',
 'Q2_4_1_2_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 분(1순위)',
 'Q2_4_2_1_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 시간(2순위)',
 'Q2_4_2_2_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 분(2순위)',
 'Q2_4_3_1_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 시간(3순위)',
 'Q2_4_3_2_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 분(3순위)',
 'Q2_4_4_1_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 시간(4순위)',
 'Q2_4_4_2_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 분(4순위)',
 'Q2_4_5_1_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 시간(5순위)',
 'Q2_4_5_2_N': '지난 1년간 가장 많이 참여한 여가활동 1회 여가 소요시간 - 분(5순위)',
 'Q2_5_1_N': '지난 1년간 가장 많이 참여한 여가활동 1회 기준 비용(1순위)',
 'Q2_5_2_N': '지난 1년간 가장 많이 참여한 여가활동 1회 기준 비용(2순위)',
 'Q2_5_3_N': '지난 1년간 가장 많이 참여한 여가활동 1회 기준 비용(3순위)',
 'Q2_5_4_N': '지난 1년간 가장 많이 참여한 여가활동 1회 기준 비용(4순위)',
 'Q2_5_5_N': '지난 1년간 가장 많이 참여한 여가활동 1회 기준 비용(5순위)',
 'Q2_6_1': '지난 1년간 가장 많이 참여한 여가활동 만족도(1순위)',
 'Q2_6_2': '지난 1년간 가장 많이 참여한 여가활동 만족도(2순위)',
 'Q2_6_3': '지난 1년간 가장 많이 참여한 여가활동 만족도(3순위)',
 'Q2_6_4': '지난 1년간 가장 많이 참여한 여가활동 만족도(4순위)',
 'Q2_6_5': '지난 1년간 가장 많이 참여한 여가활동 만족도(5순위)',
 'Q3': '여가활동 주 목적',
 'Q3_T': '여가활동 주 목적 - 기타',
 'Q4_1': '가장 만족스런 여가활동 (1순위)',
 'Q4_2': '가장 만족스런 여가활동 (2순위)',
 'Q4_3': '가장 만족스런 여가활동 (3순위)',
 'Q5': '여가경력- 반복참여 경험',
 'Q6': '지속적으로 참여하는 여가활동 중 가장 많이하는 활동',
 'Q6_T': '지속적으로 참여하는 여가활동 중 가장 많이하는 활동 - 상세유형 (주관식)',
 'Q7_1_N': '지속적/반복적으로 참여하는 여가활동 - 참여기간(년)',
 'Q7_2_N': '지속적/반복적으로 참여하는 여가활동 - 참여기간(개월)',
 'Q8': '여가활동을 위한 별도의 지식,정보 습득여부',
 'Q9_N': '지난 1년간 여가활동을 위한 지출액(월 평균)',
 'Q9_1': '지난 1년간 지출한 여가비의 충분도',
 'Q10_N': '적절하다고 생각하는 여가비용(월 평균)',
 'Q11_1_A': '평일에 참여한 여가활동 -A. 문화예술 관람 활동',
 'Q11_3_A': '평일에 희망하는 여가활동 -A. 문화예술 관람 활동',
 'Q12_1_A': '휴일에 참여한 여가활동 -A. 문화예술 관람 활동',
 'Q12_3_A': '휴일에 희망하는 여가활동 -A. 문화예술 관람 활동',
 'Q11_1_B': '평일에 참여한 여가활동 -B. 문화예술 참여 활동',
 'Q11_3_B': '평일에 희망하는 여가활동 -B. 문화예술 참여 활동',
 'Q12_1_B': '휴일에 참여한 여가활동 -B. 문화예술 참여 활동',
 'Q12_3_B': '휴일에 희망하는 여가활동 -B. 문화예술 참여 활동',
 'Q11_1_C': '평일에 참여한 여가활동 -C. 스포츠 관람 활동',
 'Q11_3_C': '평일에 희망하는 여가활동 -C. 스포츠 관람 활동',
 'Q12_1_C': '휴일에 참여한 여가활동 -C. 스포츠 관람 활동',
 'Q12_3_C': '휴일에 희망하는 여가활동 -C. 스포츠 관람 활동',
 'Q11_1_D': '평일에 참여한 여가활동 -D. 스포츠 참여 활동',
 'Q11_3_D': '평일에 희망하는 여가활동 -D. 스포츠 참여 활동',
 'Q12_1_D': '휴일에 참여한 여가활동 -D. 스포츠 참여 활동',
 'Q12_3_D': '휴일에 희망하는 여가활동 -D. 스포츠 참여 활동',
 'Q11_1_E': '평일에 참여한 여가활동 -E. 관광활동',
 'Q11_3_E': '평일에 희망하는 여가활동 -E. 관광활동',
 'Q12_1_E': '휴일에 참여한 여가활동 -E. 관광활동',
 'Q12_3_E': '휴일에 희망하는 여가활동 -E. 관광활동',
 'Q11_1_F': '평일에 참여한 여가활동 -F. 취미오락 활동',
 'Q11_3_F': '평일에 희망하는 여가활동 -F. 취미오락 활동',
 'Q12_1_F': '휴일에 참여한 여가활동 -F. 취미오락 활동',
 'Q12_3_F': '휴일에 희망하는 여가활동 -F. 취미오락 활동',
 'Q11_1_G': '평일에 참여한 여가활동 -G. 휴식활동',
 'Q11_3_G': '평일에 희망하는 여가활동 -G. 휴식활동',
 'Q12_1_G': '휴일에 참여한 여가활동 -G. 휴식활동',
 'Q12_3_G': '휴일에 희망하는 여가활동 -G. 휴식활동',
 'Q11_1_H': '평일에 참여한 여가활동 -H. 사회 및 기타 활동',
 'Q11_3_H': '평일에 희망하는 여가활동 -H. 사회 및 기타 활동',
 'Q12_1_H': '휴일에 참여한 여가활동 -H. 사회 및 기타 활동',
 'Q12_3_H': '휴일에 희망하는 여가활동 -H. 사회 및 기타 활동',
 'Q11_2_A': '평일에 참여한 여가활동 만족도 -A. 문화예술 관람 활동',
 'Q11_2_B': '평일에 참여한 여가활동 만족도 -B. 문화예술 참여 활동',
 'Q11_2_C': '평일에 참여한 여가활동 만족도 -C. 스포츠 관람 활동',
 'Q11_2_D': '평일에 참여한 여가활동 만족도 -D. 스포츠 참여 활동',
 'Q11_2_E': '평일에 참여한 여가활동 만족도 -E. 관광활동',
 'Q11_2_F': '평일에 참여한 여가활동 만족도 -F. 취미오락 활동',
 'Q11_2_G': '평일에 참여한 여가활동 만족도 -G. 휴식활동',
 'Q11_2_H': '평일에 참여한 여가활동 만족도 -H. 사회 및 기타 활동',
 'Q12_2_A': '휴일에 참여한 여가활동 만족도 -A. 문화예술 관람 활동',
 'Q12_2_B': '휴일에 참여한 여가활동 만족도 -B. 문화예술 참여 활동',
 'Q12_2_C': '휴일에 참여한 여가활동 만족도 -C. 스포츠 관람 활동',
 'Q12_2_D': '휴일에 참여한 여가활동 만족도 -D. 스포츠 참여 활동',
 'Q12_2_E': '휴일에 참여한 여가활동 만족도 -E. 관광활동',
 'Q12_2_F': '휴일에 참여한 여가활동 만족도 -F. 취미오락 활동',
 'Q12_2_G': '휴일에 참여한 여가활동 만족도 -G. 휴식활동',
 'Q12_2_H': '휴일에 참여한 여가활동 만족도 -H. 사회 및 기타 활동',
 'Q13_1_1_N': '지난 1년 간 하루 평균 여가시간 - 평일',
 'Q13_1_2_N': '지난 1년 간 하루 평균 여가시간 - 휴일',
 'Q13_2_1': '지난 1년 간 여가시간 충분도 - 평일',
 'Q13_2_2': '지난 1년 간 여가시간 충분도 - 휴일',
 'Q13_3_1': '지난 1년 간 여가시간 자유도 - 평일',
 'Q13_3_2': '지난 1년 간 여가시간 자유도 - 휴일',
 'Q13_4_1_N': '평균 여가 희망시간 - 평일',
 'Q13_4_2_N': '평균 여가 희망시간 - 휴일',
 'Q14': '지난 1년 간 휴가 사용 여부',
 'Q14_1_N': '지난 1년 간 실제 사용 휴가 일수 - 전체',
 'Q14_2_1_N': '지난 1년 간 실제 사용 휴가 일수 - 가을',
 'Q14_2_2_N': '지난 1년 간 실제 사용 휴가 일수 - 겨울',
 'Q14_2_3_N': '지난 1년 간 실제 사용 휴가 일수 - 봄',
 'Q14_2_4_N': '지난 1년 간 실제 사용 휴가 일수 - 여름',
 'Q14_3_1': '휴가기간 중 주 여가활동(1순위)',
 'Q14_3_2': '휴가기간 중 주 여가활동(2순위)',
 'Q14_3_3': '휴가기간 중 주 여가활동(3순위)',
 'Q15_1': '집 외 가장 많이 이용한 여가공간 (1순위)',
 'Q15_2': '집 외 가장 많이 이용한 여가공간 (2순위)',
 'Q15_3': '집 외 가장 많이 이용한 여가공간 (3순위)',
 'Q16_1': '집 외 가장 많이 이용하고 싶은 여가공간 (1순위)',
 'Q16_2': '집 외 가장 많이 이용하고 싶은 여가공간 (2순위)',
 'Q16_3': '집 외 가장 많이 이용하고 싶은 여가공간 (3순위)',
 'Q17_1': '생활권 내 공공문화 및 여가시설 존재 인식',
 'Q17_2': '생활권 내 공공문화 및 여가시설 이용 충분도',
 'Q17_3': '생활권 내 공공문화 및 여가시설 프로그램 인지도',
 'Q17_4': '생활권 내 공공문화 및 여가시설 프로그램 충분도',
 'Q18': '생활권 내 공공문화여가시설 이용여부',
 'Q19': '생활권 내 공공 문화여가시설 만족도',
 'Q20_1': '민간 여가산업 만족도- 여가 관련 공간산업',
 'Q20_2': '민간 여가산업 만족도- 여가 관련 용품산업',
 'Q20_3': '민간 여가산업 만족도- 여가 관련 서비스산업',
 'Q21': '지난 1년간 여가활동을 위한 동호회 참여 여부',
 'Q21_1': '참여 동호회 주된 활동',
 'Q21_1_T': '참여 동호회 주된 활동(상세내용)',
 'Q21_2': '참여 동호회 부수적 활동',
 'Q21_2_T': '참여 동호회 부수적 활동(상세내용)',
 'Q22': '지난 1년간 자원봉사 참여 경험',
 'Q22_1_1': '활동한 자원봉사 분야 (복수응답) - 문화자원봉사 관련',
 'Q22_1_2': '활동한 자원봉사 분야 (복수응답) - 환경보전, 범죄예방 등과 관련',
 'Q22_1_3': '활동한 자원봉사 분야 (복수응답) - 국가 및 지역 행사 등과 관련',
 'Q22_1_4': '활동한 자원봉사 분야 (복수응답) - 아동, 청소년, 노인, 장애인, 재소자 등과 관련(복지시설,병원, 개인가정 봉사, 야학교사 등)',
 'Q22_1_5': '활동한 자원봉사 분야 (복수응답) - 재해지역 주민 돕기 및 시설복구 등과 관련',
 'Q22_1_6': '활동한 자원봉사 분야 (복수응답) - 일반인을 위한 봉사 관련(무료상담, 아이돌보기 등)',
 'Q22_1_7': '활동한 자원봉사 분야 (복수응답) - 기타',
 'Q22_1_T': '활동한 자원봉사 분야 (복수응답) - 기타(상세내용)',
 'Q23_1_N': '여가시간 중 스마트기기 이용 시간 - 평일',
 'Q23_2_N': '여가시간 중 스마트기기 이용 시간 - 휴일',
 'Q24': '스마트기기 이용 시 가장 많이하는 여가활동',
 'Q24_T': '스마트기기 이용 시 가장 많이하는 여가활동 - 기타(상세내용)',
 'Q25_1': '여가 정책 중요도- 여가시설의 다양성',
 'Q25_2': '여가 정책 중요도- 질 좋은 여가프로그램 개발 및 보급',
 'Q25_3': '여가 정책 중요도- 여가관련 전문인력 양성 및 배치',
 'Q25_4': '여가 정책 중요도- 여가관련 동호회 육성 및 지원',
 'Q25_5': '여가 정책 중요도- 소외계층 여가생활 지원',
 'Q25_6': '여가 정책 중요도- 여가관련 법규와 제도 개선',
 'Q25_7': '여가 정책 중요도- 공휴일과 휴가를 법적 보장',
 'Q25_1_1': '여가 정책 중요도 순위 (1순위)',
 'Q25_1_2': '여가 정책 중요도 순위 (2순위)',
 'Q25_1_3': '여가 정책 중요도 순위 (3순위)',
 'Q26_1': '여가 정책 만족도 - 여가시설의 다양성',
 'Q26_2': '여가 정책 만족도 - 질 좋은 여가프로그램 개발 및 보급',
 'Q26_3': '여가 정책 만족도 - 여가관련 전문인력 양성 및 배치',
 'Q26_4': '여가 정책 만족도 - 여가관련 동호회 육성 및 지원',
 'Q26_5': '여가 정책 만족도 - 소외계층 여가생활 지원',
 'Q26_6': '여가 정책 만족도 - 여가관련 법규와 제도 개선',
 'Q26_7': '여가 정책 만족도 - 공휴일과 휴가를 법적 보장',
 'Q27': '일(학업)과 여가의 균형',
 'Q28': '더 많은 시간이 주어질 시 활용 계획',
 'Q28_T': '더 많은 시간이 주어질 시 활용 계획 - 기타',
 'Q29': '전반적 여가생활 만족도',
 'Q29_1': '여가생활 불만족 이유',
 'Q29_1_T': '여가생활 불만족 이유 - 기타',
 'Q30': '여가인식 - 여가활동이 삶의 필수적인 요건이다',
 'Q31': '여가인식 - 여가활동이 삶의 긍정적 영향을 끼치는 지 여부',
 'Q32': '현재 행복 수준 - 10점 척도',
 'Q33': '본인의 건강상태 인식',
 'Q34_1': '여가활동 제약요인 - 시간부족',
 'Q34_2': '여가활동 제약요인 - 경제적 지출 부담',
 'Q34_3': '여가활동 제약요인 - 미세먼지',
 'Q34_4': '여가활동 제약요인 - 폭염이나 폭한',
 'Q34_5': '여가활동 제약요인 - 가족의 건강(질병, 장애 등)',
 'Q34_6': '여가활동 제약요인 - 안전 (치안 등)',
 'Q34_7': '여가활동 제약요인 - 코로나19',
 'Q35': '재직여부',
 'Q36': '현재 근무지 주 52시간 근무제도 시행 여부',
 'Q36_1_1_1': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-1 - 체육활동을 통한 건강 증진',
 'Q36_1_1_2': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-2 - 여가활동을 통한 개인적 즐거움 및 자기만족 증대',
 'Q36_1_1_3': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-3 - 휴식을 통한 정서적 신체적 안정',
 'Q36_1_1_4': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-4 - 대인관계 및 교제를 위한 시간 증대',
 'Q36_1_1_5': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-5 - 가족과 함께하는 시간 증대',
 'Q36_1_1_6': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-6 - 업무 효율성 향상',
 'Q36_1_1_7': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-7 - 추가적인 직업/부업 구함',
 'Q36_1_1_8': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-8 - 가족 간 갈등과 불화 심화',
 'Q36_1_1_9': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-9 - 자유시간 증가에 따른 심리적 부담',
 'Q36_1_1_10': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-10 - 여가활동 증가로 피곤함 경험',
 'Q36_1_1_11': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-11 - 수입 감소',
 'Q36_1_1_12': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-12 - 제한된 시간 내 업무로 인한 업무 압박 및 강도 증가',
 'Q36_1_1_13': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-13 - 가사노동 부담 증가',
 'Q36_1_1_14': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-14 - 별다른 변화 없음',
 'Q36_1_1_15': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-15 - 기타',
 'Q36_1_1_T': '주 52시간 근무제도 시행 후 생활 변화 복수응답 (문36 예 응답자)-기타 주관식 응답',
 'Q36_2_1': '주 52시간 근무제도 시행 후 여가 만족도 (문36 예 응답자)',
 'Q36_1_2_1': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -1 - 체육활동을 통한 건강 증진',
 'Q36_1_2_2': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -2 - 여가활동을 통한 개인적 즐거움 및 자기만족 증대',
 'Q36_1_2_3': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -3 - 휴식을 통한 정서적 신체적 안정',
 'Q36_1_2_4': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -4 - 대인관계 및 교제를 위한 시간 증대',
 'Q36_1_2_5': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -5 - 가족과 함께하는 시간 증대',
 'Q36_1_2_6': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -6 - 업무 효율성 향상',
 'Q36_1_2_7': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -7 - 추가적인 직업/부업 구함',
 'Q36_1_2_8': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -8 - 가족 간 갈등과 불화 심화',
 'Q36_1_2_9': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -9 - 자유시간 증가에 따른 심리적 부담',
 'Q36_1_2_10': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -10 - 여가활동 증가로 피곤함 경험',
 'Q36_1_2_11': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -11 - 수입 감소',
 'Q36_1_2_12': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -12 - 제한된 시간 내 업무로 인한 업무 압박 및 강도 증가',
 'Q36_1_2_13': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -13 - 가사노동 부담 증가',
 'Q36_1_2_14': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -14 - 별다른 변화 없음',
 'Q36_1_2_15': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -15 - 기타',
 'Q36_1_2_T': '주 52시간 근무제도 시행 시 예상되는 생활 변화 복수응답 (문36 아니오 응답자) -기타 주관식 응답',
 'Q36_2_2': '주 52시간 근무제도 시행 시 예상되는 여가 만족도 (문36 아니오 응답자)',
 'Q37_1': '주 52시간 근무제도 시행(예정) 후 가장 하고 싶은 여가활동 (1순위)',
 'Q37_2': '주 52시간 근무제도 시행(예정) 후 가장 하고 싶은 여가활동 (2순위)',
 'Q37_3': '주 52시간 근무제도 시행(예정) 후 가장 하고 싶은 여가활동 (3순위)',
 'Q38_1': '본인의 교육정도 - 최종학력',
 'Q43_4': '가구주의 학력 - 최종학력',
 'Q38_2': '본인의 교육정도 - 이수여부',
 'Q43_5': '가구주의 학력 - 이수여부',
 'Q39': '혼인상태',
 'Q39_T': '혼인상태 - 기타',
 'Q40_N': '만 나이',
 'Q41_1_N': '전체 동거 가구원 수',
 'Q41_2_N': '만 15세 이상 동거 가구원 수',
 'Q41_1_1': '동거 자녀 현황 (복수응답1) - 자녀 없음',
 'Q41_1_2': '동거 자녀 현황 (복수응답2) - 미취학아동 자녀(0세~만 5세 이하)',
 'Q41_1_3': '동거 자녀 현황 (복수응답3) - 취학 자녀(만 6세 ~ 만 18세 이하)',
 'Q41_1_4': '동거 자녀 현황 (복수응답4) - 성인 자녀(만 19세 이상)',
 'Q41_1_2_N': '미취학아동 자녀 수',
 'Q41_1_3_N': '취학 자녀 수',
 'Q41_1_4_N': '성인 자녀 수',
 'Q42': '가구주 여부',
 'Q42_1': '가구주와의 관계',
 'Q42_2': '응답자 성별',
 'Q42_3': '가구주의 성별',
 'Q43_1': '응답자 장애등록 여부',
 'Q43_2': '응답자 본인 외 가족 장애등록 여부',
 'Q43_1_1': '응답자 장애정도',
 'Q43_2_1': '응답자 본인 외 가족 장애정도',
 'Q44': '지난 1주일 간 경제활동 여부',
 'Q44_1_1': '경제활동 한 경우 직업 - 주업',
 'Q45_1_2': '경제활동 한 경우 직업 - 부업',
 'Q44_2': '경제활동 없는 경우 - 직업',
 'Q44_3': '종사상의 지위',
 'Q44_4_N': '주당 평균 근무 시간',
 'Q44_5': '현재 근무지 주 5일제 시행 여부',
 'Q44_6': '직장내 근무형태',
 'Q44_7': '유연근무제 시행 여부',
 'Q45_1': '지난 1년 간 세금 공제 전 월 평균 소득- 본인',
 'Q45_2': '지난 1년 간 세금 공제 전 월 평균 소득- 가구',
 'WT': '가중치',
 'DM1': '성별',
 'DM2': '연령',
 'DM3': '학력',
 'DM4': '동거 가구원수(전체)',
 'DM5': '혼인상태',
 'DM6': '가구주 여부',
 'DM7': '종사상 지위',
 'DM8': '가구소득',
 'DM9': '지역규모',
 'DM10': '권역',
 'DM11': '지역(시도)',
 'DM12': '장애여부',
 'DM19': '근무형태',
 'DM20': '유연근무제 여부'}

### 데이터 전처리2
base자료와 지난 1년간 가장 많이 참여한 여가활동데이터프레임을 분리  
분리한 데이터에도 ID부여

In [ ]:
# 파일 읽어오기 - 에러발생시 현재 파일과 상대파일 경로 꼭! 재확인!
db1_df = pd.read_excel("../../data/지난 1년간 가장 많이 참여한 여가활동.xlsx")

# 우리가 가진 데이터에서 base값은 91번컬럼까지있으니 확인!
base_df = db1_df.iloc[:,:92]
culture_df = db1_df.iloc[:,92:]

display(base_df.head())
display(culture_df.head())

,ID,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q1_8,Q1_9,...,Q1_82,Q1_83,Q1_84,Q1_85,Q1_86,Q1_87,Q1_88,Q1_89,Q1_90,Q1_91
0,1001005.0,0,0,0,1,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1001008.0,0,1,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1001010.0,0,0,0,0,0,0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1001018.0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1001025.0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

   Q2_1_1  Q2_1_2  Q2_1_3  Q2_1_4  Q2_1_5
0    25.0    81.0    71.0    53.0    44.0
1    74.0     2.0     2.0     3.0     1.0
2    58.0    73.0     7.0     1.0     1.0
3    77.0    74.0    51.0    31.0     1.0
4    72.0    52.0     2.0     2.0     3.0

In [ ]:
# culture_df에도 ID(유저) 추가 - 추후 맵핑위해서!
culture_df['ID'] = db1_df['ID']

culture_df = culture_df[['ID'] + culture_df.columns[:-1].tolist()]

culture_df

             ID  Q2_1_1  Q2_1_2  Q2_1_3  Q2_1_4  Q2_1_5
0     1001005.0    25.0    81.0    71.0    53.0    44.0
1     1001008.0    74.0     2.0     2.0     3.0     1.0
2     1001010.0    58.0    73.0     7.0     1.0     1.0
3     1001018.0    77.0    74.0    51.0    31.0     1.0
4     1001025.0    72.0    52.0     2.0     2.0     3.0
...         ...     ...     ...     ...     ...     ...
9662  2477060.0    71.0    75.0    58.0    32.0    63.0
9663  2477061.0    75.0    74.0    63.0    83.0    64.0
9664  2477062.0    71.0    14.0    48.0    16.0    20.0
9665  2477063.0    88.0    52.0    71.0    75.0    55.0
9666  2477064.0    84.0    71.0    72.0    55.0    86.0

[9667 rows x 6 columns]

### 데이터전처리3
여가활동코드 딕셔너리에 저장

In [7]:
# 엑셀 파일을 읽어옵니다
code_culture_df = pd.read_excel("../../data/여가유형.xlsx")  # 파일 경로를 지정하세요

# 데이터프레임을 리스트로 변환합니다
culture_data_list = code_culture_df.values.tolist()

# code_dict에 키-값 형태로 코드와 정보를 저장
culture_code_dict = {}

for key, value in culture_data_list:
    culture_code_dict[key] = value

culture_code_dict

{1: ' 전시회 관람(미술, 사진, 건축, 디자인 등)',
 2: ' 박물관 관람',
 3: ' 음악연주회 관람(클래식, 오페라 등)',
 4: ' 전통예술공연 관람(국악, 민속놀이 등)',
 5: ' 연극공연 관람(뮤지컬 포함)',
 6: ' 무용공연 관람',
 7: ' 영화관람',
 8: ' 연예공연 관람(쇼, 콘서트, 마술 쇼 등)',
 9: ' 문학행사참여',
 10: ' 글짓기/독서토론',
 11: ' 미술활동(그림, 서예, 조각, 디자인, 도예, 만화 등)',
 12: ' 악기연주/노래교실',
 13: ' 전통예술 배우기(사물놀이, 줄타기 등)',
 14: ' 사진촬영(디지털카메라 포함)',
 15: ' 춤/무용(발레, 한국무용, 현대무용, 방송댄스, 스트릿댄스, 비보잉 등)',
 16: ' 스포츠 경기 직접관람- 경기장방문관람(축구, 야구,농구, 배구 등)',
 17: ' 스포츠 경기 간접관람- TV, DMB를 통한관람(축구, 야구, 농구, 배구 등)',
 18: ' 격투 스포츠 경기관람(태권도, 유도, 합기도, 검도,권투 등)',
 19: ' 온라인게임 경기관람(e-스포츠 경기 포함)',
 20: ' 농구, 배구, 야구, 축구, 족구',
 21: ' 테니스, 스쿼시',
 22: ' 당구/포켓볼',
 23: ' 볼링, 탁구',
 24: ' 골프',
 25: ' 수영',
 26: ' 윈드서핑, 수상스키, 스킨스쿠버다이빙, 래프팅, 요트',
 27: ' 스노보드, 스키 등',
 28: ' 아이스스케이트, 아이스하키 등',
 29: ' 헬스(보디빌딩)/에어로빅',
 30: ' 요가/필라테스/태보',
 31: ' 배드민턴/줄넘기/맨손, 스트레칭 체조/훌라후프',
 32: ' 육상/조깅/속보',
 33: ' 격투 스포츠(태권도, 유도, 합기도, 검도, 권투 등)',
 34: ' 댄스스포츠(탱고, 왈츠, 자이브, 맘보,폴카, 차차차등)',
 35: ' 사이클링/산악자전거',
 36: ' 인라인스케이트',
 37: ' 승마, 암벽등반, 철인삼종경기, 서바이벌',
 38: ' 문화유적방문(고궁, 절, 유적지 등)',
 39: ' 자연명승 및 풍경 관람',
 40: ' 삼림욕',
 41: ' 국내캠핑',
 42: ' 해외여행',
 43: ' 소풍/야유회',
 44: ' 온천/해수욕',
 45: ' 유람선 타기',
 46: ' 테마파크가기/놀이공원/동물원/식물원 가기',
 47: ' 지역축제 참가',
 48: ' 자동차 드라이브',
 49: ' 수집활동(스크랩 포함)',
 50: ' 생활공예(십자수, 비즈공예, D.I.Y, 꽃꽂이 등)',
 51: ' 요리하기/다도',
 52: ' 반려동물 돌보기',
 53: ' 노래방 가기',
 54: ' 인테리어(집, 자동차 등)',
 55: ' 등산',
 56: ' 낚시',
 57: ' 홈페이지/블로그 관리',
 58: ' 인터넷 검색/1인 미디어 제작/SNS/영상편집',
 59: ' 게임(온라인/모바일/콘솔게임 등)',
 60: ' 보드게임/퍼즐/큐브 맞추기',
 61: ' 바둑/장기/체스',
 62: ' 겜블(경마, 경륜, 카지노, 카드놀이, 고스톱, 마작 등)/복권구입',
 63: ' 쇼핑/외식',
 64: ' 음주',
 65: ' 독서(웹소설 포함)',
 66: ' 만화보기(웹툰 포함)',
 67: ' 미용(피부관리, 헤어관리, 네일아트, 마사지, 성형 등)',
 68: ' 어학/기술/자격증 취득 공부/학원 등 이용',
 69: ' 이색/테마카페 체험(방탈출, VR, 낚시카페 등)',
 70: ' 원예(화분, 화단가꾸기 등)',
 71: ' 산책 및 걷기',
 72: ' 목욕/사우나/찜질방',
 73: ' 낮잠',
 74: ' TV시청(IPTV 포함)',
 75: ' 모바일 컨텐츠, 동영상, VOD 시청, OTT 시청',
 76: ' 라디오/팟캐스트 청취',
 77: ' 음악 감상',
 78: ' 신문/잡지보기',
 79: ' 아무것도 안 하기',
 80: ' 사회봉사활동',
 81: ' 종교활동',
 82: ' 클럽/나이트/디스코/캬바레 가기',
 83: ' 가족 및 친지방문',
 84: ' 잡담/통화하기/문자보내기(모바일 메신저 메시지 사용 포함)',
 85: ' 계모임/동창회/사교(파티)모임',
 86: ' 친구만남/이성교제/미팅/소개팅',
 87: ' 동호회 모임',
 88: ' 위에서 분류되지 않은 기타 여가활동',
 89: ' 독서/만화책(웹툰)보기(2014,2016,2018)',
 90: ' 이성교제(데이트)/미팅/소개팅(2014,2016,2018)',
 91: ' 친구만남/동호회 모임(2014,2016,2018)',
 99: ' 무응답'}

### TEST

테스트데이터로 유사한 사람의 1년간 가장 많이 참여한 여가활동 추출
-> 여가활동 추천 시스템

In [5]:
import numpy as np
import pandas as pd
from numpy import dot
from numpy.linalg import norm

# 코사인 유사도 함수 정의
def cos_sim(A, B):
    return dot(A, B) / (norm(A) * norm(B))

# 데이터 로드 및 3000개 샘플링 (예시)
data_vectors = db1_df.select_dtypes(include=[np.number]).iloc[:3000].values  # 숫자형 데이터만 사용
data_ids = db1_df['ID'][:3000].values  # 3000개의 ID 추출

# data_vectors의 벡터 길이에 맞춘 테스트 벡터 생성
vector_length = data_vectors.shape[1]
user_input_vector = np.random.randint(2, size=vector_length)

print("테스트 벡터:", user_input_vector)

# 입력 벡터와 각 데이터 벡터 간의 유사도를 계산하여 리스트에 저장
similarities = []
for i in range(len(data_vectors)):
    similarity = cos_sim(user_input_vector, data_vectors[i])
    similarities.append((data_ids[i], similarity))  # (ID, 유사도) 형태로 저장

# 유사도에 따라 내림차순 정렬
similarities.sort(key=lambda x: x[1], reverse=True)

# 상위 N개의 유사한 문서 추출 (예: 상위 5개)
top_n = 5
top_n_similarities = similarities[:top_n]

user_culture = {}

# 출력
print("사용자 입력과 가장 유사한 상위 5개 문서:")
for doc_id, sim in top_n_similarities:
    print(f"문서 ID: {doc_id}, 유사도: {sim}")
    user_culture[doc_id] = []
    row_index = 0  # 원하는 행의 인덱스 설정

    # 값이 1인 열 이름 추출
    columns_with_ones = db1_df.columns[db1_df[db1_df['ID'] == doc_id].iloc[row_index] == 1].tolist()

    for column in columns_with_ones:
        try:
            # code_dict에서 column 키가 존재하는 경우에만 추가
            user_culture[doc_id].append(code_dict[column])
        except KeyError:
            # code_dict에 키가 없는 경우 예외 처리
            print(f"Warning: {column} 키가 code_dict에 존재하지 않습니다.")
            # 필요한 경우 다른 대체값을 추가할 수 있습니다.
            user_culture[doc_id].append(None)  # None으로 빈 값 추가

print(user_culture)

테스트 벡터: [0 1 1 0 0 0 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 1 1 0 0 1 0
 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 0 1 1 0 0 0 1
 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 1 0]
사용자 입력과 가장 유사한 상위 5개 문서:
문서 ID: 1070058.0, 유사도: 1.4313078351509762e-05
문서 ID: 1061052.0, 유사도: 1.3747204691118251e-05
문서 ID: 1073077.0, 유사도: 1.3593152218728983e-05
문서 ID: 1063051.0, 유사도: 1.3584140426570673e-05
문서 ID: 1053067.0, 유사도: 1.3435901081379289e-05
{np.float64(1070058.0): ['전시회 관람(미술, 사진, 건축, 디자인 등)', '박물관 관람', '연극공연 관람(뮤지컬 포함)', '영화관람', '연예공연 관람(쇼, 콘서트, 마술 쇼 등)', '미술활동(그림, 서예, 조각, 디자인, 도예, 만화 등)', '스포츠 경기 직접관람- 경기장방문관람(축구, 야구,농구, 배구 등)', '스포츠 경기 간접관람- TV, DMB를 통한관람(축구, 야구, 농구, 배구 등)', '당구/포켓볼', '볼링, 탁구', '수영', '스노보드, 스키 등', '격투 스포츠(태권도, 유도, 합기도, 검도, 권투 등)', '문화유적방문(고궁, 절, 유적지 등)', '국내캠핑', '테마파크가기/놀이공원/동물원/식물원 가기', '자동차 드라이브', '반려동물 돌보기', '노래방 가기', '인터넷 검색/1인 미디어 제작/SNS/영상편집', '게임(온라인/모바일/콘솔게임 등)', '보드게임/퍼즐/큐브 맞추기', '쇼핑/외식', '음주', '미용(피부관리, 헤어관리, 네일아트, 마사지, 성형 등)', '어학/기술/자격증 취득 공부/학원 등 이용', '산책 및 걷기', '목욕/사우나/찜질방', '낮잠', 'TV시청(IPTV 포함)', '모바일 컨텐츠, 동영상, VOD 시청, OTT 시청', '라디오/팟캐스트 청취', '음악 감상', '가족 및 친지방문', '잡담/통화하기/문자보내기(모바일 메신저 메시지 사용 포함)', '계모임/동창회/사교(파티)모임', '친구만남/이성교제/미팅/소개팅'], np.float64(1061052.0): ['전시회 관람(미술, 사진, 건축, 디자인 등)', '박물관 관람', '전통예술공연 관람(국악, 민속놀이 등)', '연극공연 관람(뮤지컬 포함)', '미술활동(그림, 서예, 조각, 디자인, 도예, 만화 등)', '사진촬영(디지털카메라 포함)', '스포츠 경기 직접관람- 경기장방문관람(축구, 야구,농구, 배구 등)', '스포츠 경기 간접관람- TV, DMB를 통한관람(축구, 야구, 농구, 배구 등)', '볼링, 탁구', '수영', '아이스스케이트, 아이스하키 등', '헬스(보디빌딩)/에어로빅', '배드민턴/줄넘기/맨손, 스트레칭 체조/훌라후프', '육상/조깅/속보', '승마, 암벽등반, 철인삼종경기, 서바이벌', '문화유적방문(고궁, 절, 유적지 등)', '자연명승 및 풍경 관람', '소풍/야유회', '온천/해수욕', '유람선 타기', '테마파크가기/놀이공원/동물원/식물원 가기', '지역축제 참가', '자동차 드라이브', '요리하기/다도', '낚시', '인터넷 검색/1인 미디어 제작/SNS/영상편집', '보드게임/퍼즐/큐브 맞추기', '만화보기(웹툰 포함)', '미용(피부관리, 헤어관리, 네일아트, 마사지, 성형 등)', '어학/기술/자격증 취득 공부/학원 등 이용', '원예(화분, 화단가꾸기 등)', '산책 및 걷기', '목욕/사우나/찜질방', 'TV시청(IPTV 포함)', '모바일 컨텐츠, 동영상, VOD 시청, OTT 시청', '라디오/팟캐스트 청취', '아무것도 안 하기', '클럽/나이트/디스코/캬바레 가기', '가족 및 친지방문', '잡담/통화하기/문자보내기(모바일 메신저 메시지 사용 포함)', '친구만남/이성교제/미팅/소개팅'], np.float64(1073077.0): ['영화관람', '사진촬영(디지털카메라 포함)', '농구, 배구, 야구, 축구, 족구', '윈드서핑, 수상스키, 스킨스쿠버다이빙, 래프팅, 요트', '배드민턴/줄넘기/맨손, 스트레칭 체조/훌라후프', '격투 스포츠(태권도, 유도, 합기도, 검도, 권투 등)', '국내캠핑', '지역축제 참가', '요리하기/다도', '노래방 가기', '인터넷 검색/1인 미디어 제작/SNS/영상편집', '게임(온라인/모바일/콘솔게임 등)', '보드게임/퍼즐/큐브 맞추기', '쇼핑/외식', '음주', '만화보기(웹툰 포함)', '이색/테마카페 체험(방탈출, VR, 낚시카페 등)', '낮잠', 'TV시청(IPTV 포함)', '모바일 컨텐츠, 동영상, VOD 시청, OTT 시청', '음악 감상', '가족 및 친지방문', '잡담/통화하기/문자보내기(모바일 메신저 메시지 사용 포함)', '친구만남/이성교제/미팅/소개팅', '동호회 모임'], np.float64(1063051.0): ['영화관람', '스포츠 경기 간접관람- TV, DMB를 통한관람(축구, 야구, 농구, 배구 등)', '농구, 배구, 야구, 축구, 족구', '당구/포켓볼', '볼링, 탁구', '헬스(보디빌딩)/에어로빅', '육상/조깅/속보', '자연명승 및 풍경 관람', '국내캠핑', '소풍/야유회', '자동차 드라이브', '노래방 가기', '등산', '낚시', '인터넷 검색/1인 미디어 제작/SNS/영상편집', '게임(온라인/모바일/콘솔게임 등)', '쇼핑/외식', '음주', '이색/테마카페 체험(방탈출, VR, 낚시카페 등)', '산책 및 걷기', '목욕/사우나/찜질방', '낮잠', 'TV시청(IPTV 포함)', '모바일 컨텐츠, 동영상, VOD 시청, OTT 시청', '음악 감상', '가족 및 친지방문', '잡담/통화하기/문자보내기(모바일 메신저 메시지 사용 포함)', '친구만남/이성교제/미팅/소개팅'], np.float64(1053067.0): ['전시회 관람(미술, 사진, 건축, 디자인 등)', '박물관 관람', '스포츠 경기 간접관람- TV, DMB를 통한관람(축구, 야구, 농구, 배구 등)', '격투 스포츠 경기관람(태권도, 유도, 합기도, 검도,권투 등)', '온라인게임 경기관람(e-스포츠 경기 포함)', '육상/조깅/속보', '문화유적방문(고궁, 절, 유적지 등)', '테마파크가기/놀이공원/동물원/식물원 가기', '인터넷 검색/1인 미디어 제작/SNS/영상편집', '게임(온라인/모바일/콘솔게임 등)', '보드게임/퍼즐/큐브 맞추기', '쇼핑/외식', '음주', '독서(웹소설 포함)', '만화보기(웹툰 포함)', '미용(피부관리, 헤어관리, 네일아트, 마사지, 성형 등)', '낮잠', 'TV시청(IPTV 포함)', '모바일 컨텐츠, 동영상, VOD 시청, OTT 시청', '음악 감상', '아무것도 안 하기', '가족 및 친지방문', '잡담/통화하기/문자보내기(모바일 메신저 메시지 사용 포함)', '친구만남/이성교제/미팅/소개팅']}

In [10]:
test_df = culture_df[culture_df['ID'] == 1070058]

In [18]:
test_df

            ID  Q2_1_1  Q2_1_2  Q2_1_3  Q2_1_4  Q2_1_5
612  1070058.0    52.0    58.0    23.0    86.0    53.0

In [42]:
for idx, i in enumerate(test_df.columns[1:]):
    tmp = culture_code_dict[test_df[i].values[0]]
    print(f'{idx+1}순위 : {tmp}')

1순위 :  반려동물 돌보기
2순위 :  인터넷 검색/1인 미디어 제작/SNS/영상편집
3순위 :  볼링, 탁구
4순위 :  친구만남/이성교제/미팅/소개팅
5순위 :  노래방 가기